### Etapa 1 - Tratamento dos Dados
- Carregar dataset e realizar inspeção inicial
- Verificar tipos de dados
- Identificar valores nulos e duplicados
- Analisar estatísticas descritivas

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/dataset_analise_vendas.csv")
df

,ID_Venda,Data,Produto,Categoria,Quantidade,Preco_Unitario,Valor_Total,Cliente,Estado
0,1,2025-07-19,Cadeira Gamer,Móveis,2.0,1200.0,2400.0,Gabriel,MG
1,2,2025-08-18,Notebook,Eletrônicos,5.0,3500.0,17500.0,NaN,PB
2,3,2025-08-13,Livro Banco de Dados,Livros,1.0,120.0,120.0,Carlos,RJ
3,4,2025-04-28,NaN,Eletrônicos,1.0,350.0,350.0,Gabriel,NaN
4,5,2025-01-19,Mesa Escritório,Móveis,4.0,800.0,3200.0,Bruno,BA
...,...,...,...,...,...,...,...,...,...
495,496,2025-06-01,Smartphone,Eletrônicos,1.0,2200.0,2200.0,Fernanda,PE
496,497,2025-04-08,Curso Online,Educação,4.0,500.0,2000.0,Ana,BA
497,498,2025-01-13,Mesa Escritório,Móveis,2.0,800.0,1600.0,Fernanda,PE
498,499,2025-12-16,Notebook,Eletrônicos,5.0,NaN,17500.0,Fernanda,PR
499,500,2025-01-14,Cadeira Gamer,Móveis,2.0,1200.0,2400.0,Helena,RJ

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        500 non-null    int64
 1   Data            500 non-null    str
 2   Produto         477 non-null    str
 3   Categoria       474 non-null    str
 4   Quantidade      478 non-null    float64
 5   Preco_Unitario  479 non-null    float64
 6   Valor_Total     472 non-null    float64
 7   Cliente         470 non-null    str
 8   Estado          478 non-null    str
dtypes: float64(3), int64(1), str(5)
memory usage: 54.4 KB

In [4]:
df.describe()

         ID_Venda  Quantidade  Preco_Unitario   Valor_Total
count  500.000000  478.000000      479.000000    472.000000
mean   250.500000    2.960251      947.494781   2982.012712
std    144.481833    1.439372     1103.013553   4022.494443
min      1.000000    1.000000       90.000000     90.000000
25%    125.750000    2.000000      180.000000    480.000000
50%    250.500000    3.000000      500.000000   1200.000000
75%    375.250000    4.000000     1200.000000   3600.000000
max    500.000000    5.000000     3500.000000  17500.000000

### Etapa 2: Limpeza e Padronização
- Padronizar nomes das colunas
- Converter coluna de data str para datetime
- Remover registros duplicados
- Padronizar valores categoricos

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Venda        500 non-null    int64
 1   Data            500 non-null    str
 2   Produto         477 non-null    str
 3   Categoria       474 non-null    str
 4   Quantidade      478 non-null    float64
 5   Preco_Unitario  479 non-null    float64
 6   Valor_Total     472 non-null    float64
 7   Cliente         470 non-null    str
 8   Estado          478 non-null    str
dtypes: float64(3), int64(1), str(5)
memory usage: 54.4 KB

In [6]:
df.columns = ["id_venda", "data", "produto", "categoria", "quantidade", "preco_unitario", "valor_total", "cliente", "estado"]
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    str
 2   produto         477 non-null    str
 3   categoria       474 non-null    str
 4   quantidade      478 non-null    float64
 5   preco_unitario  479 non-null    float64
 6   valor_total     472 non-null    float64
 7   cliente         470 non-null    str
 8   estado          478 non-null    str
dtypes: float64(3), int64(1), str(5)
memory usage: 54.4 KB

In [7]:
df["data"] = pd.to_datetime(df["data"])
df.dtypes

id_venda                   int64
data              datetime64[us]
produto                      str
categoria                    str
quantidade               float64
preco_unitario           float64
valor_total              float64
cliente                      str
estado                       str
dtype: object

In [8]:
df.duplicated().sum()

np.int64(0)

### Etapa 3: Tratamento de Valores Nulos

- Tratar valores ausentes em *[ produtos ]*
- Completar *[ categorias ]* com base no *[ produto ]*
- Recuperar *[ quantidade ]* usando *[ valor_total ]* e *[ preco ]*
- Recuperar *[ preco ]* usando *[ valor_total ]* e *[ preco ]*
- Calcular *[ valor_total ]* ausente
- Preencher *[ clientes ]* nao identificados
- Preencher *[ estados ]* nao informados

In [9]:
df

,id_venda,data,produto,categoria,quantidade,preco_unitario,valor_total,cliente,estado
0,1,2025-07-19,Cadeira Gamer,Móveis,2.0,1200.0,2400.0,Gabriel,MG
1,2,2025-08-18,Notebook,Eletrônicos,5.0,3500.0,17500.0,NaN,PB
2,3,2025-08-13,Livro Banco de Dados,Livros,1.0,120.0,120.0,Carlos,RJ
3,4,2025-04-28,NaN,Eletrônicos,1.0,350.0,350.0,Gabriel,NaN
4,5,2025-01-19,Mesa Escritório,Móveis,4.0,800.0,3200.0,Bruno,BA
...,...,...,...,...,...,...,...,...,...
495,496,2025-06-01,Smartphone,Eletrônicos,1.0,2200.0,2200.0,Fernanda,PE
496,497,2025-04-08,Curso Online,Educação,4.0,500.0,2000.0,Ana,BA
497,498,2025-01-13,Mesa Escritório,Móveis,2.0,800.0,1600.0,Fernanda,PE
498,499,2025-12-16,Notebook,Eletrônicos,5.0,NaN,17500.0,Fernanda,PR
499,500,2025-01-14,Cadeira Gamer,Móveis,2.0,1200.0,2400.0,Helena,RJ

In [10]:
df["produto"] = df["produto"].fillna("Produto_Nao_Informado")
df

,id_venda,data,produto,categoria,quantidade,preco_unitario,valor_total,cliente,estado
0,1,2025-07-19,Cadeira Gamer,Móveis,2.0,1200.0,2400.0,Gabriel,MG
1,2,2025-08-18,Notebook,Eletrônicos,5.0,3500.0,17500.0,NaN,PB
2,3,2025-08-13,Livro Banco de Dados,Livros,1.0,120.0,120.0,Carlos,RJ
3,4,2025-04-28,Produto_Nao_Informado,Eletrônicos,1.0,350.0,350.0,Gabriel,NaN
4,5,2025-01-19,Mesa Escritório,Móveis,4.0,800.0,3200.0,Bruno,BA
...,...,...,...,...,...,...,...,...,...
495,496,2025-06-01,Smartphone,Eletrônicos,1.0,2200.0,2200.0,Fernanda,PE
496,497,2025-04-08,Curso Online,Educação,4.0,500.0,2000.0,Ana,BA
497,498,2025-01-13,Mesa Escritório,Móveis,2.0,800.0,1600.0,Fernanda,PE
498,499,2025-12-16,Notebook,Eletrônicos,5.0,NaN,17500.0,Fernanda,PR
499,500,2025-01-14,Cadeira Gamer,Móveis,2.0,1200.0,2400.0,Helena,RJ

- Produtos antes NaN foram substituidos pela generalizacao "Produto_Nao_Informado", visando nao perder as informacoes de vendas

In [11]:
df["categoria"].unique()

<ArrowStringArray>
['Móveis', 'Eletrônicos', 'Livros', 'Acessórios', 'Educação', nan]
Length: 6, dtype: str

In [12]:
df["produto"].unique()

<ArrowStringArray>
[        'Cadeira Gamer',              'Notebook',  'Livro Banco de Dados',
 'Produto_Nao_Informado',       'Mesa Escritório',          'Livro Python',
      'Teclado Mecânico',        'Fone Bluetooth',               'Mochila',
            'Smartphone',          'Curso Online']
Length: 11, dtype: str

In [13]:
# Imputando moveis sem categoria
df.loc[df["produto"].isin(["Cadeira Gamer", "Mesa Escritório"]), "categoria"] = "Móveis"
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    datetime64[us]
 2   produto         500 non-null    str
 3   categoria       481 non-null    str
 4   quantidade      478 non-null    float64
 5   preco_unitario  479 non-null    float64
 6   valor_total     472 non-null    float64
 7   cliente         470 non-null    str
 8   estado          478 non-null    str
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 50.0 KB

In [14]:
df.loc[df["produto"].isin(["Livro Banco de Dados", "Livro Python"]), "categoria"] = "Livros"
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    datetime64[us]
 2   produto         500 non-null    str
 3   categoria       483 non-null    str
 4   quantidade      478 non-null    float64
 5   preco_unitario  479 non-null    float64
 6   valor_total     472 non-null    float64
 7   cliente         470 non-null    str
 8   estado          478 non-null    str
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 50.0 KB

In [15]:
df.loc[df["produto"].isin(["Teclado Mecânico", "Smartphone", "Notebook", "Fone Bluetooth"]), "categoria"] = "Eletrônicos"
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    datetime64[us]
 2   produto         500 non-null    str
 3   categoria       495 non-null    str
 4   quantidade      478 non-null    float64
 5   preco_unitario  479 non-null    float64
 6   valor_total     472 non-null    float64
 7   cliente         470 non-null    str
 8   estado          478 non-null    str
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 50.1 KB

In [16]:
df.loc[df["produto"].isin(["Curso Online"]), "categoria"] = "Educação"
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    datetime64[us]
 2   produto         500 non-null    str
 3   categoria       498 non-null    str
 4   quantidade      478 non-null    float64
 5   preco_unitario  479 non-null    float64
 6   valor_total     472 non-null    float64
 7   cliente         470 non-null    str
 8   estado          478 non-null    str
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 50.1 KB

In [17]:
df.loc[df["produto"].isin(["Mochila"]), "categoria"] = "Acessórios"
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    datetime64[us]
 2   produto         500 non-null    str
 3   categoria       500 non-null    str
 4   quantidade      478 non-null    float64
 5   preco_unitario  479 non-null    float64
 6   valor_total     472 non-null    float64
 7   cliente         470 non-null    str
 8   estado          478 non-null    str
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 50.1 KB

- Campos de categoria recuperados a partir do produto

In [18]:
df

,id_venda,data,produto,categoria,quantidade,preco_unitario,valor_total,cliente,estado
0,1,2025-07-19,Cadeira Gamer,Móveis,2.0,1200.0,2400.0,Gabriel,MG
1,2,2025-08-18,Notebook,Eletrônicos,5.0,3500.0,17500.0,NaN,PB
2,3,2025-08-13,Livro Banco de Dados,Livros,1.0,120.0,120.0,Carlos,RJ
3,4,2025-04-28,Produto_Nao_Informado,Eletrônicos,1.0,350.0,350.0,Gabriel,NaN
4,5,2025-01-19,Mesa Escritório,Móveis,4.0,800.0,3200.0,Bruno,BA
...,...,...,...,...,...,...,...,...,...
495,496,2025-06-01,Smartphone,Eletrônicos,1.0,2200.0,2200.0,Fernanda,PE
496,497,2025-04-08,Curso Online,Educação,4.0,500.0,2000.0,Ana,BA
497,498,2025-01-13,Mesa Escritório,Móveis,2.0,800.0,1600.0,Fernanda,PE
498,499,2025-12-16,Notebook,Eletrônicos,5.0,NaN,17500.0,Fernanda,PR
499,500,2025-01-14,Cadeira Gamer,Móveis,2.0,1200.0,2400.0,Helena,RJ

In [19]:
df["quantidade"] = df["quantidade"].fillna(df["valor_total"] / df["preco_unitario"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    datetime64[us]
 2   produto         500 non-null    str
 3   categoria       500 non-null    str
 4   quantidade      499 non-null    float64
 5   preco_unitario  479 non-null    float64
 6   valor_total     472 non-null    float64
 7   cliente         470 non-null    str
 8   estado          478 non-null    str
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 50.1 KB

In [20]:
df[df["quantidade"].isnull()]

,id_venda,data,produto,categoria,quantidade,preco_unitario,valor_total,cliente,estado
32,33,2025-09-18,Notebook,Eletrônicos,NaN,NaN,14000.0,Ana,MG

- Alguns campos de *[ preco_unitario ]* estao NaN, mas temos a informacao do preco unitario de cada produto

In [21]:
df["produto"].unique()

<ArrowStringArray>
[        'Cadeira Gamer',              'Notebook',  'Livro Banco de Dados',
 'Produto_Nao_Informado',       'Mesa Escritório',          'Livro Python',
      'Teclado Mecânico',        'Fone Bluetooth',               'Mochila',
            'Smartphone',          'Curso Online']
Length: 11, dtype: str

In [22]:
precos = {
    "Cadeira Gamer": 1200,
    "Teclado Mecânico": 350,
    "Smartphone": 2200,
    "Notebook": 3500,
    "Mesa Escritório": 800,
    "Fone Bluetooth": 250,
    "Curso Online": 500,
    "Livro Banco de Dados": 120,
    "Livro Python": 90,
    "Mochila": 180
}

In [23]:
df["preco_unitario"] = df["preco_unitario"].fillna(
    df["produto"].map(precos)
)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    datetime64[us]
 2   produto         500 non-null    str
 3   categoria       500 non-null    str
 4   quantidade      499 non-null    float64
 5   preco_unitario  500 non-null    float64
 6   valor_total     472 non-null    float64
 7   cliente         470 non-null    str
 8   estado          478 non-null    str
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 50.1 KB

- Campos de *[ preco_unitario ]* tratado, valores NaN substituidos pelos valores corretos

In [25]:
df["quantidade"] = df["quantidade"].fillna(df["valor_total"] / df["preco_unitario"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    datetime64[us]
 2   produto         500 non-null    str
 3   categoria       500 non-null    str
 4   quantidade      500 non-null    float64
 5   preco_unitario  500 non-null    float64
 6   valor_total     472 non-null    float64
 7   cliente         470 non-null    str
 8   estado          478 non-null    str
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 50.1 KB

- Finalizacao da task: Recuperar Quantidade usando Valor_Total e Preço

In [26]:
df

,id_venda,data,produto,categoria,quantidade,preco_unitario,valor_total,cliente,estado
0,1,2025-07-19,Cadeira Gamer,Móveis,2.0,1200.0,2400.0,Gabriel,MG
1,2,2025-08-18,Notebook,Eletrônicos,5.0,3500.0,17500.0,NaN,PB
2,3,2025-08-13,Livro Banco de Dados,Livros,1.0,120.0,120.0,Carlos,RJ
3,4,2025-04-28,Produto_Nao_Informado,Eletrônicos,1.0,350.0,350.0,Gabriel,NaN
4,5,2025-01-19,Mesa Escritório,Móveis,4.0,800.0,3200.0,Bruno,BA
...,...,...,...,...,...,...,...,...,...
495,496,2025-06-01,Smartphone,Eletrônicos,1.0,2200.0,2200.0,Fernanda,PE
496,497,2025-04-08,Curso Online,Educação,4.0,500.0,2000.0,Ana,BA
497,498,2025-01-13,Mesa Escritório,Móveis,2.0,800.0,1600.0,Fernanda,PE
498,499,2025-12-16,Notebook,Eletrônicos,5.0,3500.0,17500.0,Fernanda,PR
499,500,2025-01-14,Cadeira Gamer,Móveis,2.0,1200.0,2400.0,Helena,RJ

In [27]:
df["valor_total"] = df["valor_total"].fillna(df["preco_unitario"] * df["quantidade"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    datetime64[us]
 2   produto         500 non-null    str
 3   categoria       500 non-null    str
 4   quantidade      500 non-null    float64
 5   preco_unitario  500 non-null    float64
 6   valor_total     500 non-null    float64
 7   cliente         470 non-null    str
 8   estado          478 non-null    str
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 50.1 KB

- campos NaN na coluna *[ valor_total ]* preenchidos a partir do calculo: *df["preco_unitario"]* x *df["quantidade"]*

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    datetime64[us]
 2   produto         500 non-null    str
 3   categoria       500 non-null    str
 4   quantidade      500 non-null    float64
 5   preco_unitario  500 non-null    float64
 6   valor_total     500 non-null    float64
 7   cliente         470 non-null    str
 8   estado          478 non-null    str
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 50.1 KB

In [29]:
df["cliente"] = df["cliente"].fillna("cliente_nao_informado")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    datetime64[us]
 2   produto         500 non-null    str
 3   categoria       500 non-null    str
 4   quantidade      500 non-null    float64
 5   preco_unitario  500 non-null    float64
 6   valor_total     500 non-null    float64
 7   cliente         500 non-null    str
 8   estado          478 non-null    str
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 50.6 KB

- Campos NaN na coluna *[ cliente ]* preenchidos com "cliente_nao_informado"

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    datetime64[us]
 2   produto         500 non-null    str
 3   categoria       500 non-null    str
 4   quantidade      500 non-null    float64
 5   preco_unitario  500 non-null    float64
 6   valor_total     500 non-null    float64
 7   cliente         500 non-null    str
 8   estado          478 non-null    str
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 50.6 KB

In [31]:
df["estado"] = df["estado"].fillna("ED")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    datetime64[us]
 2   produto         500 non-null    str
 3   categoria       500 non-null    str
 4   quantidade      500 non-null    float64
 5   preco_unitario  500 non-null    float64
 6   valor_total     500 non-null    float64
 7   cliente         500 non-null    str
 8   estado          500 non-null    str
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 50.6 KB

- Campos NaN na coluna *[ estado ]* preenchidos com "ED" (Estado Desconhecido)

### Etapa 4: Validação dos Dados
- Validar regra: Quantidade x Preço = Valor_Total
- Verificar valores negativos ou inválidos
- Garantir consistência dos tipos de dados
- Confirmar que não existem valores nulos restantes

In [38]:
df.head(10)

,id_venda,data,produto,categoria,quantidade,preco_unitario,valor_total,cliente,estado
0,1,2025-07-19,Cadeira Gamer,Móveis,2.0,1200.0,2400.0,Gabriel,MG
1,2,2025-08-18,Notebook,Eletrônicos,5.0,3500.0,17500.0,cliente_nao_informado,PB
2,3,2025-08-13,Livro Banco de Dados,Livros,1.0,120.0,120.0,Carlos,RJ
3,4,2025-04-28,Produto_Nao_Informado,Eletrônicos,1.0,350.0,350.0,Gabriel,ED
4,5,2025-01-19,Mesa Escritório,Móveis,4.0,800.0,3200.0,Bruno,BA
5,6,2025-10-29,Livro Python,Livros,2.0,90.0,180.0,Eduardo,CE
6,7,2025-05-24,Teclado Mecânico,Eletrônicos,4.0,350.0,1400.0,Eduardo,SP
7,8,2025-01-28,Fone Bluetooth,Eletrônicos,5.0,250.0,1250.0,Gabriel,SP
8,9,2025-01-22,Cadeira Gamer,Móveis,2.0,1200.0,2400.0,Bruno,PB
9,10,2025-11-20,Livro Banco de Dados,Livros,2.0,120.0,240.0,Carlos,PB

##### Linhas aleatorias para validar a regra
- linha [5]: Qtd(2) x pre_uni(90) = val_tot(180)

In [40]:
valores_negativos = df[df["quantidade"] < 0]
valores_negativos

Empty DataFrame
Columns: [id_venda, data, produto, categoria, quantidade, preco_unitario, valor_total, cliente, estado]
Index: []

##### Tabela Vazia
- Nao ha valores negativos na quantidade de vendas

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        500 non-null    int64
 1   data            500 non-null    datetime64[us]
 2   produto         500 non-null    str
 3   categoria       500 non-null    str
 4   quantidade      500 non-null    float64
 5   preco_unitario  500 non-null    float64
 6   valor_total     500 non-null    float64
 7   cliente         500 non-null    str
 8   estado          500 non-null    str
dtypes: datetime64[us](1), float64(3), int64(1), str(4)
memory usage: 50.6 KB

##### Tipos corretos

In [43]:
df.isnull().sum()

id_venda          0
data              0
produto           0
categoria         0
quantidade        0
preco_unitario    0
valor_total       0
cliente           0
estado            0
dtype: int64

##### Nao ha mais campos nulos